name: salawat_app
description: تطبيق الصلاة على النبي

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.6.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^21.0.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  http: ^1.5.0
  geolocator: ^14.0.2
  quran_library: ^4.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
    - assets/salawat.mp3
    - assets/azkar.json
    - assets/azaan.mp3
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
