/// نموذج بيانات السورة القرآنية
class SurahModel {
  final int number;
  final String name;
  final int page;
  final String type;
  final int verses;

  const SurahModel({
    required this.number,
    required this.name,
    required this.page,
    required this.type,
    required this.verses,
  });
}

/// قائمة السور القرآنية الـ 114
const List<SurahModel> surahList = [
  SurahModel(number: 1, name: 'الفاتحة', page: 1, type: 'مكية', verses: 7),
  SurahModel(number: 2, name: 'البقرة', page: 2, type: 'مدنية', verses: 286),
  SurahModel(number: 3, name: 'آل عمران', page: 50, type: 'مدنية', verses: 200),
  SurahModel(number: 4, name: 'النساء', page: 77, type: 'مدنية', verses: 176),
  SurahModel(number: 5, name: 'المائدة', page: 106, type: 'مدنية', verses: 120),
  SurahModel(number: 6, name: 'الأنعام', page: 128, type: 'مكية', verses: 165),
  SurahModel(number: 7, name: 'الأعراف', page: 151, type: 'مكية', verses: 206),
  SurahModel(number: 8, name: 'الأنفال', page: 177, type: 'مدنية', verses: 75),
  SurahModel(number: 9, name: 'التوبة', page: 187, type: 'مدنية', verses: 129),
  SurahModel(number: 10, name: 'يونس', page: 208, type: 'مكية', verses: 109),
  SurahModel(number: 11, name: 'هود', page: 221, type: 'مكية', verses: 123),
  SurahModel(number: 12, name: 'يوسف', page: 235, type: 'مكية', verses: 111),
  SurahModel(number: 13, name: 'الرعد', page: 249, type: 'مدنية', verses: 43),
  SurahModel(number: 14, name: 'إبراهيم', page: 255, type: 'مكية', verses: 52),
  SurahModel(number: 15, name: 'الحجر', page: 262, type: 'مكية', verses: 99),
  SurahModel(number: 16, name: 'النحل', page: 267, type: 'مكية', verses: 128),
  SurahModel(number: 17, name: 'الإسراء', page: 282, type: 'مكية', verses: 111),
  SurahModel(number: 18, name: 'الكهف', page: 293, type: 'مكية', verses: 110),
  SurahModel(number: 19, name: 'مريم', page: 305, type: 'مكية', verses: 98),
  SurahModel(number: 20, name: 'طه', page: 312, type: 'مكية', verses: 135),
  SurahModel(number: 21, name: 'الأنبياء', page: 322, type: 'مكية', verses: 112),
  SurahModel(number: 22, name: 'الحج', page: 332, type: 'مدنية', verses: 78),
  SurahModel(number: 23, name: 'المؤمنون', page: 342, type: 'مكية', verses: 118),
  SurahModel(number: 24, name: 'النور', page: 350, type: 'مدنية', verses: 64),
  SurahModel(number: 25, name: 'الفرقان', page: 359, type: 'مكية', verses: 77),
  SurahModel(number: 26, name: 'الشعراء', page: 367, type: 'مكية', verses: 227),
  SurahModel(number: 27, name: 'النمل', page: 377, type: 'مكية', verses: 93),
  SurahModel(number: 28, name: 'القصص', page: 385, type: 'مكية', verses: 88),
  SurahModel(number: 29, name: 'العنكبوت', page: 396, type: 'مكية', verses: 69),
  SurahModel(number: 30, name: 'الروم', page: 404, type: 'مكية', verses: 60),
  SurahModel(number: 31, name: 'لقمان', page: 411, type: 'مكية', verses: 34),
  SurahModel(number: 32, name: 'السجدة', page: 415, type: 'مكية', verses: 30),
  SurahModel(number: 33, name: 'الأحزاب', page: 418, type: 'مدنية', verses: 73),
  SurahModel(number: 34, name: 'سبأ', page: 428, type: 'مكية', verses: 54),
  SurahModel(number: 35, name: 'فاطر', page: 434, type: 'مكية', verses: 45),
  SurahModel(number: 36, name: 'يس', page: 440, type: 'مكية', verses: 83),
  SurahModel(number: 37, name: 'الصافات', page: 446, type: 'مكية', verses: 182),
  SurahModel(number: 38, name: 'ص', page: 453, type: 'مكية', verses: 88),
  SurahModel(number: 39, name: 'الزمر', page: 458, type: 'مكية', verses: 75),
  SurahModel(number: 40, name: 'غافر', page: 467, type: 'مكية', verses: 85),
  SurahModel(number: 41, name: 'فصلت', page: 477, type: 'مكية', verses: 54),
  SurahModel(number: 42, name: 'الشورى', page: 483, type: 'مكية', verses: 53),
  SurahModel(number: 43, name: 'الزخرف', page: 489, type: 'مكية', verses: 89),
  SurahModel(number: 44, name: 'الدخان', page: 496, type: 'مكية', verses: 59),
  SurahModel(number: 45, name: 'الجاثية', page: 499, type: 'مكية', verses: 37),
  SurahModel(number: 46, name: 'الأحقاف', page: 502, type: 'مكية', verses: 35),
  SurahModel(number: 47, name: 'محمد', page: 507, type: 'مدنية', verses: 38),
  SurahModel(number: 48, name: 'الفتح', page: 511, type: 'مدنية', verses: 29),
  SurahModel(number: 49, name: 'الحجرات', page: 515, type: 'مدنية', verses: 18),
  SurahModel(number: 50, name: 'ق', page: 518, type: 'مكية', verses: 45),
  SurahModel(number: 51, name: 'الذاريات', page: 520, type: 'مكية', verses: 60),
  SurahModel(number: 52, name: 'الطور', page: 523, type: 'مكية', verses: 49),
  SurahModel(number: 53, name: 'النجم', page: 526, type: 'مكية', verses: 62),
  SurahModel(number: 54, name: 'القمر', page: 528, type: 'مكية', verses: 55),
  SurahModel(number: 55, name: 'الرحمن', page: 531, type: 'مدنية', verses: 78),
  SurahModel(number: 56, name: 'الواقعة', page: 534, type: 'مكية', verses: 96),
  SurahModel(number: 57, name: 'الحديد', page: 537, type: 'مدنية', verses: 29),
  SurahModel(number: 58, name: 'المجادلة', page: 542, type: 'مدنية', verses: 22),
  SurahModel(number: 59, name: 'الحشر', page: 545, type: 'مدنية', verses: 24),
  SurahModel(number: 60, name: 'الممتحنة', page: 549, type: 'مدنية', verses: 13),
  SurahModel(number: 61, name: 'الصف', page: 551, type: 'مدنية', verses: 14),
  SurahModel(number: 62, name: 'الجمعة', page: 553, type: 'مدنية', verses: 11),
  SurahModel(number: 63, name: 'المنافقون', page: 554, type: 'مدنية', verses: 11),
  SurahModel(number: 64, name: 'التغابن', page: 556, type: 'مدنية', verses: 18),
  SurahModel(number: 65, name: 'الطلاق', page: 558, type: 'مدنية', verses: 12),
  SurahModel(number: 66, name: 'التحريم', page: 560, type: 'مدنية', verses: 12),
  SurahModel(number: 67, name: 'الملك', page: 562, type: 'مكية', verses: 30),
  SurahModel(number: 68, name: 'القلم', page: 564, type: 'مكية', verses: 52),
  SurahModel(number: 69, name: 'الحاقة', page: 566, type: 'مكية', verses: 52),
  SurahModel(number: 70, name: 'المعارج', page: 568, type: 'مكية', verses: 44),
  SurahModel(number: 71, name: 'نوح', page: 570, type: 'مكية', verses: 28),
  SurahModel(number: 72, name: 'الجن', page: 572, type: 'مكية', verses: 28),
  SurahModel(number: 73, name: 'المزمل', page: 574, type: 'مكية', verses: 20),
  SurahModel(number: 74, name: 'المدثر', page: 575, type: 'مكية', verses: 56),
  SurahModel(number: 75, name: 'القيامة', page: 577, type: 'مكية', verses: 40),
  SurahModel(number: 76, name: 'الإنسان', page: 578, type: 'مدنية', verses: 31),
  SurahModel(number: 77, name: 'المرسلات', page: 580, type: 'مكية', verses: 50),
  SurahModel(number: 78, name: 'النبأ', page: 582, type: 'مكية', verses: 40),
  SurahModel(number: 79, name: 'النازعات', page: 583, type: 'مكية', verses: 46),
  SurahModel(number: 80, name: 'عبس', page: 585, type: 'مكية', verses: 42),
  SurahModel(number: 81, name: 'التكوير', page: 586, type: 'مكية', verses: 29),
  SurahModel(number: 82, name: 'الانفطار', page: 587, type: 'مكية', verses: 19),
  SurahModel(number: 83, name: 'المطففين', page: 587, type: 'مكية', verses: 36),
  SurahModel(number: 84, name: 'الانشقاق', page: 589, type: 'مكية', verses: 25),
  SurahModel(number: 85, name: 'البروج', page: 590, type: 'مكية', verses: 22),
  SurahModel(number: 86, name: 'الطارق', page: 591, type: 'مكية', verses: 17),
  SurahModel(number: 87, name: 'الأعلى', page: 591, type: 'مكية', verses: 19),
  SurahModel(number: 88, name: 'الغاشية', page: 592, type: 'مكية', verses: 26),
  SurahModel(number: 89, name: 'الفجر', page: 593, type: 'مكية', verses: 30),
  SurahModel(number: 90, name: 'البلد', page: 594, type: 'مكية', verses: 20),
  SurahModel(number: 91, name: 'الشمس', page: 595, type: 'مكية', verses: 15),
  SurahModel(number: 92, name: 'الليل', page: 595, type: 'مكية', verses: 21),
  SurahModel(number: 93, name: 'الضحى', page: 596, type: 'مكية', verses: 11),
  SurahModel(number: 94, name: 'الشرح', page: 596, type: 'مكية', verses: 8),
  SurahModel(number: 95, name: 'التين', page: 597, type: 'مكية', verses: 8),
  SurahModel(number: 96, name: 'العلق', page: 597, type: 'مكية', verses: 19),
  SurahModel(number: 97, name: 'القدر', page: 598, type: 'مكية', verses: 5),
  SurahModel(number: 98, name: 'البينة', page: 598, type: 'مدنية', verses: 8),
  SurahModel(number: 99, name: 'الزلزلة', page: 599, type: 'مدنية', verses: 8),
  SurahModel(number: 100, name: 'العاديات', page: 599, type: 'مكية', verses: 11),
  SurahModel(number: 101, name: 'القارعة', page: 600, type: 'مكية', verses: 11),
  SurahModel(number: 102, name: 'التكاثر', page: 600, type: 'مكية', verses: 8),
  SurahModel(number: 103, name: 'العصر', page: 601, type: 'مكية', verses: 3),
  SurahModel(number: 104, name: 'الهمزة', page: 601, type: 'مكية', verses: 9),
  SurahModel(number: 105, name: 'الفيل', page: 601, type: 'مكية', verses: 5),
  SurahModel(number: 106, name: 'قريش', page: 602, type: 'مكية', verses: 4),
  SurahModel(number: 107, name: 'الماعون', page: 602, type: 'مكية', verses: 7),
  SurahModel(number: 108, name: 'الكوثر', page: 602, type: 'مكية', verses: 3),
  SurahModel(number: 109, name: 'الكافرون', page: 603, type: 'مكية', verses: 6),
  SurahModel(number: 110, name: 'النصر', page: 603, type: 'مدنية', verses: 3),
  SurahModel(number: 111, name: 'المسد', page: 603, type: 'مكية', verses: 5),
  SurahModel(number: 112, name: 'الإخلاص', page: 604, type: 'مكية', verses: 4),
  SurahModel(number: 113, name: 'الفلق', page: 604, type: 'مكية', verses: 5),
  SurahModel(number: 114, name: 'الناس', page: 604, type: 'مكية', verses: 6),
];
